version: "3.5"

services:
  database-service:
    container_name: mongodb
    build:
      context: .
      dockerfile: Dockerfile
    image: mongodb 
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_ADMIN_NAME=admin
      - MONGO_INITDB_ADMIN_PASSWORD=admin-pass
      - MONGO_INITDB_USER_NAME=user
      - MONGO_INITDB_USER_PASSWORD=userpassword
      - MONGO_INITDB_DATABASE=mongodb
    volumes:
      - "./mongodb/data:/data/db"
    ports:
      - "27017:27017"