FROM mongo:4.4.7

ARG MONGO_INITDB_ROOT_PASSWORD
ARG MONGO_INITDB_ROOT_USERNAME
ARG MONGO_INITDB_ADMIN_NAME
ARG MONGO_INITDB_ADMIN_PASSWORD
ARG MONGO_INITDB_USER_NAME
ARG MONGO_INITDB_USER_PASSWORD
ARG MONGO_INITDB_DATABASE

ADD ./mongodb/create-user.js /utils/
ADD ./mongodb/mongo-init.sh /docker-entrypoint-initdb.d/

CMD [ "mongod", "--auth" ]

